server:
  port: 8080

spring:
  application:
    name: chatbot-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors-origins:
    - http://localhost:3000
    - http://localhost:18082
    - http://127.0.0.1:18082
    - https://pidima.com
  llm-provider: dummy # dummy | openai | bedrock
  llm-model: dummy-model
  persistence: dynamodb # memory | dynamodb
  # OpenAI configuration (used when llm-provider=openai)
  openai-api-key: ${OPENAI_API_KEY:}
  openai-base-url: https://api.openai.com/v1
